# group_vars/containers.yml
# Algemene instellingen voor LXC-containers (WordPress basis)

# Template & storage
ostemplate: "cephfs:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst"
storage: "rbd"
disk_size: 30   # GB

# Resources
cores: 2
memory: 2048    # MB
swap: 0

# Netwerk
bridge: "vmbr0"
ip_prefix: "10.24.28."
ip_cidr: "/24"
gw: "10.24.28.1"
firewall: true

# Container gedrag
unprivileged: true
onboot: true

# Authenticatie
root_password: "changeme123"
enable_root_pw_login: True  


container_plan:
  - node: pve1
    vmid: 150
    ip_last: 150   
    hostname: docker-150  
  - node: pve2
    vmid: 151
    ip_last: 151
    hostname: docker-151
  - node: pve3
    vmid: 152
    ip_last: 152
    hostname: docker-152